# Состояния для ConversationHandler
(
    AWAITING_SURNAME, AWAITING_NAME, AWAITING_PATRONYMIC, AWAITING_DOB, AWAITING_ROOM,
    AWAITING_REG_CONFIRMATION, AWAITING_EMAIL, AWAITING_EMAIL_CODE, AWAITING_RULES_ACK,
    MAIN_MENU,
    BOOKING_FILTER_SETUP, VIEWING_SLOTS, AWAITING_SLOT_CONFIRMATION,
    VIEWING_HISTORY, AWAITING_CANCEL_CONFIRMATION
) = range(15)